//! `solgrid migrate --from solhint` command.
//!
//! Reads a solhint config file (.solhint.json or .solhintrc) and generates
//! an equivalent solgrid.toml configuration.

use std::collections::HashMap;
use std::path::Path;

/// Run the migrate command.
pub fn run(from: &str) -> i32 {
    match from {
        "solhint" => migrate_from_solhint(),
        other => {
            eprintln!("Unknown migration source: {other}");
            eprintln!("Supported: solhint");
            1
        }
    }
}

fn migrate_from_solhint() -> i32 {
    // Look for .solhint.json or .solhintrc
    let config_path = if Path::new(".solhint.json").exists() {
        ".solhint.json"
    } else if Path::new(".solhintrc").exists() {
        ".solhintrc"
    } else {
        eprintln!("No .solhint.json or .solhintrc found in current directory");
        return 1;
    };

    let content = match std::fs::read_to_string(config_path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("Error reading {config_path}: {e}");
            return 1;
        }
    };

    let solhint: serde_json::Value = match serde_json::from_str(&content) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("Error parsing {config_path}: {e}");
            return 1;
        }
    };

    let mut rules = HashMap::new();
    let mut unmapped = Vec::new();

    if let Some(solhint_rules) = solhint.get("rules").and_then(|r| r.as_object()) {
        for (key, value) in solhint_rules {
            let severity = match value {
                serde_json::Value::String(s) => s.clone(),
                serde_json::Value::Array(arr) => arr
                    .first()
                    .and_then(|v| v.as_str())
                    .unwrap_or("warn")
                    .to_string(),
                _ => "warn".to_string(),
            };

            let level = match severity.as_str() {
                "error" => "error",
                "warn" | "warning" => "warn",
                "off" => "off",
                _ => "warn",
            };

            if let Some(solgrid_id) = map_solhint_rule(key) {
                rules.insert(solgrid_id.to_string(), level.to_string());
            } else {
                unmapped.push(key.clone());
            }
        }
    }

    // Generate solgrid.toml
    let mut output = String::new();
    output.push_str("# Generated by: solgrid migrate --from solhint\n");
    output.push_str("# Review and adjust settings as needed.\n\n");

    if !rules.is_empty() {
        output.push_str("[lint.rules]\n");
        let mut sorted_rules: Vec<_> = rules.iter().collect();
        sorted_rules.sort_by_key(|(k, _)| (*k).clone());
        for (rule_id, level) in sorted_rules {
            output.push_str(&format!("\"{rule_id}\" = \"{level}\"\n"));
        }
    }

    // Write to solgrid.toml
    let output_path = "solgrid.toml";
    if Path::new(output_path).exists() {
        eprintln!("solgrid.toml already exists. Remove it first or merge manually.");
        return 1;
    }

    match std::fs::write(output_path, &output) {
        Ok(()) => {
            eprintln!("Created {output_path} with {} rule(s) mapped", rules.len());
        }
        Err(e) => {
            eprintln!("Error writing {output_path}: {e}");
            return 1;
        }
    }

    if !unmapped.is_empty() {
        eprintln!(
            "\nWarning: {} solhint rule(s) have no solgrid equivalent:",
            unmapped.len()
        );
        for rule in &unmapped {
            eprintln!("  - {rule}");
        }
    }

    0
}

/// Map a solhint rule name to a solgrid rule ID.
/// Returns None for rules that have no equivalent.
fn map_solhint_rule(solhint_rule: &str) -> Option<&'static str> {
    match solhint_rule {
        // Security
        "avoid-tx-origin" => Some("security/tx-origin"),
        "avoid-sha3" => Some("security/avoid-sha3"),
        "avoid-suicide" => Some("security/avoid-suicide"),
        "state-visibility" => Some("security/state-visibility"),
        "no-inline-assembly" => Some("security/no-inline-assembly"),
        "avoid-low-level-calls" => Some("security/low-level-calls"),
        "reentrancy" => Some("security/reentrancy"),
        "avoid-selfdestruct" => Some("security/avoid-selfdestruct"),
        "compiler-version" | "compiler-gt-0_4" => Some("security/compiler-version"),
        "not-rely-on-block-hash" => Some("security/not-rely-on-block-hash"),
        "not-rely-on-time" => Some("security/not-rely-on-time"),
        "multiple-sends" => Some("security/multiple-sends"),

        // Best practices
        "no-console" => Some("best-practices/no-console"),
        "no-empty-blocks" => Some("best-practices/no-empty-blocks"),
        "no-unused-vars" => Some("best-practices/no-unused-vars"),
        "no-unused-import" | "no-unused-imports" => Some("best-practices/no-unused-imports"),
        "code-complexity" => Some("best-practices/code-complexity"),
        "function-max-lines" => Some("best-practices/function-max-lines"),
        "max-states-count" => Some("best-practices/max-states-count"),
        "one-contract-per-file" => Some("best-practices/one-contract-per-file"),
        "no-global-import" => Some("best-practices/no-global-import"),
        "reason-string" => Some("best-practices/reason-string"),
        "custom-errors" => Some("best-practices/custom-errors"),
        "no-floating-pragma" => Some("best-practices/no-floating-pragma"),
        "imports-on-top" => Some("best-practices/imports-on-top"),
        "visibility-modifier-order" => Some("best-practices/visibility-modifier-order"),

        // Naming
        "contract-name-camelcase" => Some("naming/contract-name-capwords"),
        "func-name-mixedcase" => Some("naming/func-name-mixedcase"),
        "const-name-snakecase" => Some("naming/const-name-snakecase"),
        "private-vars-leading-underscore" => Some("naming/private-vars-underscore"),
        "use-forbidden-name" | "var-name-mixedcase" => Some("naming/var-name-mixedcase"),
        "event-name-camelcase" => Some("naming/event-name-capwords"),
        "modifier-name-mixedcase" => Some("naming/modifier-name-mixedcase"),
        "named-parameters-mapping" => None,
        "immutable-vars-naming" => Some("naming/immutable-name-snakecase"),

        // Gas
        "gas-custom-errors" => Some("gas/custom-errors"),
        "gas-calldata-parameters" => Some("gas/calldata-parameters"),
        "gas-increment-by-one" => Some("gas/increment-by-one"),
        "gas-indexed-events" => Some("gas/indexed-events"),
        "gas-named-return-values" => Some("gas/named-return-values"),
        "gas-struct-packing" => Some("gas/struct-packing"),

        // Style
        "max-line-length" => Some("style/max-line-length"),
        "no-trailing-whitespace" | "no-mix-tabs-and-spaces" => Some("style/no-trailing-whitespace"),
        "ordering" => Some("style/ordering"),
        "category-headers" => Some("style/category-headers"),
        "import-order-separation" => Some("style/imports-ordering"),
        "natspec" | "natspec-triple-slash" => Some("docs/natspec"),
        "selector-tags" => Some("docs/selector-tags"),

        _ => None,
    }
}
