#!/usr/bin/env bash
#
# rules-doc.sh — generate or verify docs/rules.md from `solgrid list-rules`
#
# Usage:
#   ./scripts/rules-doc.sh --write   # Regenerate docs/rules.md
#   ./scripts/rules-doc.sh --check   # Fail if docs/rules.md is out of date
#

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="$REPO_ROOT/docs/rules.md"

usage() {
  echo "Usage:"
  echo "  $0 --write    Regenerate docs/rules.md"
  echo "  $0 --check    Verify docs/rules.md is up to date"
  exit 1
}

MODE="${1:-}"
if [[ "$MODE" != "--write" && "$MODE" != "--check" ]]; then
  usage
fi

RULES_OUTPUT="$(cd "$REPO_ROOT" && cargo run -q -p solgrid -- list-rules)"
TOTAL_RULES="$(printf '%s\n' "$RULES_OUTPUT" | awk '/ rules available$/ {print $1}')"

if [[ -z "$TOTAL_RULES" ]]; then
  echo "Error: failed to determine rule count from \`solgrid list-rules\`" >&2
  exit 1
fi

TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

emit_section() {
  local category="$1"
  local heading="$2"

  {
    echo "## $heading"
    echo
    echo "| Rule | Default Severity | Fix |"
    echo "|---|---|---|"
    printf '%s\n' "$RULES_OUTPUT" | awk -v category="$category" '
      NR > 2 && NF >= 4 && $2 == category {
        printf("| `%s` | `%s` | `%s` |\n", $1, $3, $4)
      }
    '
    echo
  } >> "$TMP_FILE"
}

{
  echo "# Rules Reference"
  echo
  echo "<!-- Generated by scripts/rules-doc.sh --write. Do not edit by hand. -->"
  echo
  echo "This document lists the currently registered solgrid rules by category, along with each rule's default severity and fix availability."
  echo
  echo "For a summary in the CLI, run:"
  echo
  echo '```bash'
  echo 'solgrid list-rules'
  echo '```'
  echo
  echo "For rule-specific details, run:"
  echo
  echo '```bash'
  echo 'solgrid explain <rule-id>'
  echo '```'
  echo
  echo "Notes:"
  echo
  echo "- The current registry contains $TOTAL_RULES active rules."
  echo "- Legacy NatSpec rule IDs such as \`best-practices/use-natspec\` are deprecated config aliases for \`docs/natspec\`, not separately registered rules."
  echo
} > "$TMP_FILE"

emit_section "security" "Security"
emit_section "best-practices" "Best Practices"
emit_section "naming" "Naming"
emit_section "gas" "Gas"
emit_section "style" "Style"
emit_section "docs" "Docs"

case "$MODE" in
  --write)
    cp "$TMP_FILE" "$TARGET"
    echo "Updated $TARGET"
    ;;
  --check)
    if diff -u "$TARGET" "$TMP_FILE" >/dev/null; then
      echo "docs/rules.md is up to date"
    else
      echo "docs/rules.md is out of date. Regenerate it with:" >&2
      echo "  bash scripts/rules-doc.sh --write" >&2
      diff -u "$TARGET" "$TMP_FILE" >&2 || true
      exit 1
    fi
    ;;
esac
