/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * JavaScript-friendly formatting options.
 *
 * Maps Prettier conventions to solgrid's internal `FormatConfig`:
 * - `print_width` → `line_length`
 * - `tab_width` → `tab_width`
 * - `use_tabs` → `use_tabs`
 * - `single_quote` → `single_quote`
 * - `bracket_spacing` → `bracket_spacing`
 */
export interface FormatOptions {
  /** Maps to solgrid `line_length`. Prettier default: 80. */
  printWidth?: number
  /** Maps to solgrid `tab_width`. Prettier default: 2. */
  tabWidth?: number
  /** Maps to solgrid `use_tabs`. Prettier default: false. */
  useTabs?: boolean
  /** Maps to solgrid `single_quote`. Prettier default: false. */
  singleQuote?: boolean
  /** Maps to solgrid `bracket_spacing`. Prettier default: true. */
  bracketSpacing?: boolean
  /** solgrid-specific: "preserve", "thousands", or "remove". */
  numberUnderscore?: string
  /** solgrid-specific: "uint256"/"long", "uint"/"short", or "preserve". */
  uintType?: string
  /** solgrid-specific: add space in override specifiers. */
  overrideSpacing?: boolean
  /** solgrid-specific: wrap comments to fit within line length. */
  wrapComments?: boolean
  /** solgrid-specific: "leading" or "trailing" multiline binary operators. */
  operatorLineBreak?: string
  /** solgrid-specific: sort import statements alphabetically. */
  sortImports?: boolean
  /** solgrid-specific: "attributes_first", "params_first", or "all". */
  multilineFuncHeader?: string
  /**
   * solgrid-specific: spacing between contract body declarations.
   * "preserve" (default), "single", or "compact".
   */
  contractBodySpacing?: string
  /** solgrid-specific: put opening brace on new line for multiline inheritance. */
  inheritanceBraceNewLine?: boolean
}
/**
 * Validate that the source is syntactically valid Solidity.
 *
 * Returns `true` if the source parses without errors, `false` otherwise.
 */
export declare function parse(source: string): boolean
/**
 * Format Solidity source code with the given options.
 *
 * Returns the formatted source string.
 * Throws on syntax errors.
 */
export declare function format(source: string, options?: FormatOptions | undefined | null): string
/**
 * Check if source is already formatted with the given options.
 *
 * Returns `true` if the source matches what the formatter would produce.
 * Throws on syntax errors.
 */
export declare function check(source: string, options?: FormatOptions | undefined | null): boolean
